# Generated by Django 4.2.1 on 2023-05-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_alter_product_options_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='publication_date',
            field=models.DateField(auto_now=True),
        ),
    ]
