# Generated by Django 4.2.1 on 2023-05-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_product_created_at_product_curse_removes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture_url',
            field=models.URLField(default='https://cs6.pikabu.ru/avatars/547/v547695-2072060446.jpg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Описание товара'),
        ),
    ]
