# Generated by Django 4.2.1 on 2023-05-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(auto_created=models.CharField(max_length=35), blank=True)),
                ('name', models.CharField(max_length=35)),
            ],
        ),
    ]
