# Generated by Django 4.2.1 on 2023-05-18 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Дата и время внесения товара в каталог'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='curse_removes',
            field=models.BooleanField(default=False, help_text='Снимает ли товар порчу и сглаз'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.SmallIntegerField(default=0, help_text='Размер скидки в процентах'),
        ),
        migrations.AddField(
            model_name='product',
            name='luck_in_business',
            field=models.BooleanField(default=False, help_text='Приносит ли товар удачу в бизнесе'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Цена за единицу товара', max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=models.CharField(help_text='Наименование товара', max_length=35), help_text='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Наименование товара', max_length=35),
        ),
    ]
